Fixup release-candidate script.
Previously the svn add of the dist artifacts failed with:
```
Publishing release candidate to https://dist.apache.org/repos/dist/dev/aurora/0.12.0-rc0
Committing transaction...
Committed revision 12061.
Checked out revision 12061.
svn: E155007: /home/jsirois/dev/3rdparty/aurora-origin is not a working copy
ERROR: Looks like something has failed while creating the release candidate.
```

Testing Done:
Tested with a slightly different diff - this successfully published to svn (since removed):
```diff
$ git diff
diff --git a/build-support/release/release-candidate b/build-support/release/release-candidate
index 78e9a4f..91261c0 100755
--- a/build-support/release/release-candidate
+++ b/build-support/release/release-candidate
@@ -93,7 +93,7 @@ git fetch --tags -q
 # Verify that this is a clean repository
 if [[ -n "`git status --porcelain`" ]]; then
   echo "ERROR: Please run from a clean git repository."
-  exit 1
+#  exit 1
 elif [[ "`git rev-parse --abbrev-ref HEAD`" != "master" ]]; then
   echo "ERROR: This script must be run from master."
   exit 1
@@ -219,8 +219,11 @@ if [[ $publish == 1 ]]; then
   echo "Publishing release candidate to ${aurora_svn_rc_url}"
   svn mkdir ${aurora_svn_rc_url} -m "aurora-${current_version} release candidate ${rc_version_tag}"
   svn co --depth=empty ${aurora_svn_rc_url} ${dist_dir}
+  pushd ${dist_dir}
   svn add ${dist_name}*
   svn ci -m "aurora-${current_version} release candidate ${rc_version_tag}"
+  popd
+  exit 0

   echo "Creating tag ${rc_version_tag}"
   git tag -s ${rc_version_tag} \
```

Reviewed at https://reviews.apache.org/r/42898/