ZookeeperSchedulerClient url property errored when no proxy_url was set, and the client was not connected.
Squashed commit of the following:

commit 964335686e57b079f28466de502fbebedd5e360c
Merge: d0b46fc 513876c
Author: Brian Wickman <wickman@twitter.com>
Date:   Mon Jan 6 10:11:19 2014 -0800

    Merge 69f4b79e4054b85b36490c04fb569e3f752dca6f to post-rename master.

commit 513876cfce07b005ef6a10ea39480bf181b7dd9b
Author: Joshua Cohen <jcohen@twitter.com>
Date:   Mon Jan 6 10:08:22 2014 -0800

    ZookeeperSchedulerClient url property errored when no proxy_url was set, and the client was not connected.

    commit 69f4b79e4054b85b36490c04fb569e3f752dca6f
    Author: Joshua Cohen <jcohen@twitter.com>
    Date:   Mon Dec 9 18:09:22 2013 -0600

        ZookeeperSchedulerClient url property errored when no proxy_url was set, and the client was not connected.

     .../twitter/aurora/client/api/scheduler_client.py  |  3 ++
     .../aurora/client/api/test_scheduler_client.py     | 56 ++++++++++++++++++++++
     2 files changed, 59 insertions(+)

    The original failure is:

      File "twitter/aurora/client/api/scheduler_client.py", line 138, in url
        if self._http:
      AttributeError: 'ZookeeperSchedulerClient' object has no attribute '_http'

    The fix presented here is to implicitly connect if we're not connected though I'm not sure if this is the desired behavior. The alternative would be to gracefully fail if cluster.proxy_url is not set and self._http is None, then leave it up to the caller to decide whether or not to connect. Connecting is generally implicit today though, so I went this way (though connecting as a result of trying to access the scheduler url may be unexpected).

    Testing Done:
    Added unit test, ./pants src/test/python/twitter/aurora/client:all

    Bugs closed: AURORA-6

    Reviewed at https://reviews.apache.org/r/16144/