Tear down the observer in case of on unhandled errors
I was not able to manually trigger the root cause of AURORA-1801 by altering the Mesos filesystem layout. I have therefore adopted the general teardown idea.

Example output (using a hardcoded throw):

```
Bottle v0.11.6 server starting up (using CherryPyServer())...
Listening on http://192.168.33.7:1338/
Hit Ctrl-C to quit.

E1106 23:03:36.722500 8699 exceptional.py:41] Unhandled error in thread Thread-1 [TID=8705]. Tearing down.
Traceback (most recent call last):
  File "apache/thermos/common/exceptional.py", line 37, in _excepting_run
    self.__real_run(*args, **kw)
  File "apache/thermos/observer/task_observer.py", line 135, in run
    self._detector.refresh()
  File "apache/thermos/observer/detector.py", line 74, in refresh
    self._refresh_detectors()
  File "apache/thermos/observer/detector.py", line 58, in _refresh_detectors
    new_paths = set(self._path_detector.get_paths())
  File "apache/aurora/executor/common/path_detector.py", line 35, in get_paths
    return list(set(path for path in iterate() if os.path.exists(path)))
  File "apache/aurora/executor/common/path_detector.py", line 35, in <genexpr>
    return list(set(path for path in iterate() if os.path.exists(path)))
  File "apache/aurora/executor/common/path_detector.py", line 34, in iterate
    raise RuntimeError("Fail on purpose...")
RuntimeError: Fail on purpose...
I1106 23:03:42.513900 8728 static_assets.py:34] detecting assets...
I1106 23:03:42.541809 8728 static_assets.py:38]   detected asset: observer.js
I1106 23:03:42.542799 8728 static_assets.py:38]   detected asset: bootstrap.css
I1106 23:03:42.543728 8728 static_assets.py:38]   detected asset: jquery.pailer.js
I1106 23:03:42.544576 8728 static_assets.py:38]   detected asset: jquery.js
I1106 23:03:42.548482 8728 static_assets.py:38]   detected asset: favicon.ico
Bottle v0.11.6 server starting up (using CherryPyServer())...
Listening on http://192.168.33.7:1338/
Hit Ctrl-C to quit.
```

Bugs closed: AURORA-1801

Reviewed at https://reviews.apache.org/r/53519/